import { NextResponse } from 'next/server'
import { ApiClientError, deleteTransaction, updateTransaction } from '@repo/shared/apiClient'
import { getSessionToken } from '@repo/shared/auth'

// Explicit Promise-typed params (not the generated `RouteContext<...>` helper)
// — that helper depends on types generated by a prior `next dev`/`next
// build`/`next typegen` pass, which this route can't assume has happened
// (design.md "Risks & Concerns": Next 16 makes route params async, same as
// cookies()/headers()).
interface RouteParams {
  params: Promise<{ id: string }>
}

// API-03: proxies PUT /account/transaction/:id.
export async function PUT(request: Request, { params }: RouteParams) {
  const token = await getSessionToken()

  if (!token) {
    return NextResponse.json({ message: 'Não autenticado.' }, { status: 401 })
  }

  const { id } = await params

  try {
    const body = await request.json()
    const updated = await updateTransaction(token, id, body)
    return NextResponse.json(updated, { status: 200 })
  } catch (error) {
    if (error instanceof ApiClientError && error.status === 401) {
      return NextResponse.json({ message: 'Sessão expirada.' }, { status: 401 })
    }
    if (error instanceof ApiClientError && error.status === 404) {
      return NextResponse.json({ message: 'Transação não encontrada.' }, { status: 404 })
    }
    if (error instanceof ApiClientError && error.status >= 400 && error.status < 500) {
      return NextResponse.json({ message: error.message }, { status: error.status })
    }
    return NextResponse.json(
      { message: 'Não foi possível atualizar a transação. Tente novamente.' },
      { status: 502 }
    )
  }
}

// API-04: proxies DELETE /account/transaction/:id. The real API responds
// 204 with no body on success — relayed as-is (design.md Error Handling
// Strategy: "DELETE retorna 204 sem corpo").
export async function DELETE(_request: Request, { params }: RouteParams) {
  const token = await getSessionToken()

  if (!token) {
    return NextResponse.json({ message: 'Não autenticado.' }, { status: 401 })
  }

  const { id } = await params

  try {
    await deleteTransaction(token, id)
    return new NextResponse(null, { status: 204 })
  } catch (error) {
    if (error instanceof ApiClientError && error.status === 401) {
      return NextResponse.json({ message: 'Sessão expirada.' }, { status: 401 })
    }
    if (error instanceof ApiClientError && error.status === 404) {
      return NextResponse.json({ message: 'Transação não encontrada.' }, { status: 404 })
    }
    return NextResponse.json(
      { message: 'Não foi possível excluir a transação. Tente novamente.' },
      { status: 502 }
    )
  }
}
